version: "3"

services:
  app:
    build: .
    image: "public.ecr.aws/citizensadvice/mokta"
    ports:
      - 4001:4001
    volumes:
      - .:/app
      - ./spec/fixtures/form:/app/form
    environment:
      - URL_HOST=app.test:4001
      - MOKTA_ISSUER=https://cadev.oktapreview.com
